BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[HealthCheck] (
    [id] INT NOT NULL IDENTITY(1,1),
    [message] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [HealthCheck_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [HealthCheck_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
